config/routes.rb
Rishi::Application.routes.draw do
  
  get "/sitemap.:format", :to =>"sitemap#index"

  get "pages/index"
  root :to => 'pages#index'
  
  get '/blog' => 'pages#blog' #index
  get '/blog/post/:id' => 'pages#post', :as => :blog_post #indivdual post
  get '/blog/category/:category_name' => 'pages#bycategory', :as=> :blog_category #filtering by category
  
  get 'blog/search' => 'pages#search', :as=> :blog_search
  
  get '/thesis' => 'pages#thesis'
  get '/thesis/:id' => 'pages#thesis_article', :as => :thesis_article
  
  get '/projects' => 'pages#projects'

  get '/project/:id' => 'pages#project', :as => :project
  
  get 'blog/archive' => 'pages#archive'
  
  get '/colophon' => 'pages#colophon'
  
  get "/store" => "store#index"
    

  resources :orders, :line_items, :carts

  devise_for :users
  
  match "/admin", :to=>"admin#index"
  
  namespace :admin do
    resources :categories, :product_categories, :traits, :variants, :posts
    resources :products do 
      resources :variants
    end
     
  end

  match 'admin/orders' => "orders#index"

 

end

app/views/admin/index.html.erb
<%= title "Admin"%>
<div class="well">
<h1>Admin</h1>
<hr>

<div class="row">
<span class="span7">
<h3>Recent Activity</h3>
<% unless @posts.empty? %>
<% @posts.each do |post| %>
  <% if post.has_draft? %>
  <span class="label label-warning">DRAFT</span> 
  <%end%> 
  <%= post.title %> published at <%= post.created_at.to_s(:short) %><br/>
<%end%>
<% @orders.each do |order| %>
  <%= order.firstname %> <%= order.lastname %> placed an order on <%= order.created_at.to_s(:short) %><br/>
<%end%>

<hr>
<%end%>
</span>
</div>

<div class="row">

<span class="span3">
<h2>Posts</h2>

<%= link_to "Add a Post", new_admin_post_path %><br/>
<%= link_to "Add a post category", new_admin_category_path  %><br/>
<%= link_to "Manage Posts", admin_posts_path%><br/>
</span>

<span class="span3">
<h2>Store</h2>
<%= link_to "Add a Product", new_admin_product_path%> <br/>
<%= link_to "Add a Product Category", new_admin_product_category_path%> <br/>
<%= link_to "Add a Product Trait", new_admin_trait_path%> <br />
<%= link_to "Manage Catalog", admin_products_path%><br/>

<%= link_to "View Orders", admin_orders_path%>
</span>
</div>

</div>