config/routes.rb
Rishi::Application.routes.draw do
  
  get "/sitemap.:format", :to =>"sitemap#index"

  get "pages/index"
  root :to => 'pages#index'
  
  get '/blog' => 'pages#blog' #index
  get '/blog/post/:id' => 'pages#post', :as => :blog_post #indivdual post
  get '/blog/category/:category_name' => 'pages#bycategory', :as=> :blog_category #filtering by category
  
  get 'blog/search' => 'pages#search', :as=> :blog_search
  
  get '/thesis' => 'pages#thesis'
  get '/thesis/:id' => 'pages#thesis_article', :as => :thesis_article
  
  get '/projects' => 'pages#projects'

  get '/project/:id' => 'pages#project', :as => :project
  
  get 'blog/archive' => 'pages#archive'
  
  get '/colophon' => 'pages#colophon'
  
  get "/store" => "store#index"
    

  resources :orders, :line_items, :carts

  devise_for :users
  
  match "/admin", :to=>"admin#index"
  
  namespace :admin do
    resources :categories, :product_categories, :traits, :variants, :posts
    resources :products do 
      resources :variants
    end
     
  end

  match 'admin/orders' => "orders#index"

 

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_and_belongs_to_many :posts
  validates :category_name, :category_description, :presence => true
  
  def self.filter_category(params)
    where("category_name NOT IN (?)", params)
  end
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

before_filter :authenticate_user!
layout 'admin_layout'

 #authenticate user
 before_filter :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= title "#{controller.action_name.capitalize} #{controller_name.singularize.capitalize}"%> 
<%= form_for [:admin,@category], :html => { :class => 'form-horizontal' } do |f| %>

<% if @category.errors.any? %>
<div class="alert alert-error">
	<h2><%= pluralize(@category.errors.count, "error") %> prohibited this product from being saved:</h2>
	<ul>
		<% @category.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

  
    
    <div class="well">
    <legend><%= controller.action_name.capitalize %> Categories</legend>
      <%= f.label :category_name %>
      <%= f.text_field :category_name %>
      <br><br>

      <%= f.label :category_description %>
      <%= f.text_area :category_description,  :rows=>10, :class=>"span8" %>
      
      <br><br>

    
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_categories_path, :class => 'btn' %>
     </div>
 
<% end %>

app/views/admin/categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/admin/categories/index.html.erb
<%= title "Manage #{controller_name.singularize.capitalize}"%>
<h1>Categories</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Category name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= link_to category.category_name, admin_category_path(category) %></td>
        <td><%= category.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_admin_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', admin_category_path(category), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_admin_category_path, :class => 'btn btn-primary' %>

app/views/admin/categories/new.html.erb
<%= render :partial => 'form' %>

app/views/admin/categories/show.html.erb
<h1>Category</h1>

<p>
  <b>Category name</b><br>
  <%= @category.category_name %>
</p>

<p>
  <b>Category description</b><br>
  <%= @category.category_description %>
</p>

<div class="form-actions">
  <%= link_to 'Back', admin_categories_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_admin_category_path(@category), :class => 'btn' %>
  <%= link_to 'Delete', admin_category_path(@category), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>