config/routes.rb
Rishi::Application.routes.draw do
  
  get "/sitemap.:format", :to =>"sitemap#index"

  get "pages/index"
  root :to => 'pages#index'
  
  get '/blog' => 'pages#blog' #index
  get '/blog/post/:id' => 'pages#post', :as => :blog_post #indivdual post
  get '/blog/category/:category_name' => 'pages#bycategory', :as=> :blog_category #filtering by category
  
  get 'blog/search' => 'pages#search', :as=> :blog_search
  
  get '/thesis' => 'pages#thesis'
  get '/thesis/:id' => 'pages#thesis_article', :as => :thesis_article
  
  get '/projects' => 'pages#projects'

  get '/project/:id' => 'pages#project', :as => :project
  
  get 'blog/archive' => 'pages#archive'
  
  get '/colophon' => 'pages#colophon'
  
  get "/store" => "store#index"
    

  resources :orders, :line_items, :carts

  devise_for :users
  
  match "/admin", :to=>"admin#index"
  
  namespace :admin do
    resources :categories, :product_categories, :traits, :variants, :posts
    resources :products do 
      resources :variants
    end
     
  end

  match 'admin/orders' => "orders#index"

 

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  validates :name, :description, :presence=>true
  validates :name, :uniqueness => true
 
  #categories
  has_and_belongs_to_many :product_categories
  accepts_nested_attributes_for :product_categories
  
  #variants
  has_many :variants, :dependent => :destroy
  
  #attached photos
  has_many :product_shots, :dependent => :destroy
  accepts_nested_attributes_for :product_shots, :allow_destroy => true,
                                :reject_if => proc { |attributes| attributes['shot'].blank? } 
  
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  before_filter :authenticate_user!
  layout 'admin_layout'
  def index
    @products =  Product.find(:all)
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @variant = @product.variants.find(params[:id])
    @attribution = @variant.attributions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    4.times{@product.product_shots.build}
    @variant = @product.variants.new
    @trait = @variant.traits.new
    
        
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    params[:product][:product_category_ids] ||= [] 
    @product = Product.find(params[:id])
    
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_products_url, :notice => 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= title "#{controller.action_name.capitalize} #{controller_name.singularize.capitalize}"%>
<%= nested_form_for([:admin,@product],  :html => {:multipart => true}) do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
	<ul>
		<% @product.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="well">
<legend><%=controller.action_name.capitalize %> Product</legend>
	<%= f.label :name %>
	<%= f.text_field :name %>


	<%= f.label :product_category_id %>
	<div class="form-inline">
	<%= hidden_field_tag "product[product_category_ids][]", nil %>
	<% ProductCategory.all.each do |category| %>

		<%= check_box_tag "product[product_category_ids][]", category.id, @product.product_categories.include?(category) %>
		<%= label_tag dom_id(category), category.title %><br>
	
	<% end %>
	</div>
</div>

<!-- attached photo -->
<%= render :partial=> "shots_form", :locals =>{:f=> f} %>

<div class="well">

	<%= f.label :description %>
	<%= f.text_area :description, :class=> "span8", :rows=>10 %>

<br><br>
<%= f.submit :class=>"btn btn-primary"%>
</div>
<% end %> 

app/views/admin/products/_shots_form.erb
	  
  <div class="field" id="attachments">
  <%= f.label "Product Shots" %>  <br>	
 
  <%= f.fields_for :product_shots do |pshot| %>
  
  <% if pshot.object.new_record? %>
  <%= pshot.file_field :shot %>
  <%end%>
    

  
  <% unless pshot.object.new_record? %>
  	<%= link_to image_tag(pshot.object.shot.url(:thumb)), pshot.object.shot.url(:medium)%><br>
	<%= pshot.object.shot.url(:medium)%><br>	
	<%= link_to_function "Insert image into description", "insertMarkup(this,'image')", :class=> "insert-image-markup"%>
 <%end%>
  
   
  <%= pshot.link_to_remove "Remove this image", {:id=> @product.id} %> <br><br>
  
   <%end %>	
  
  <%= f.link_to_add "Add another image", :product_shots %>  
  </div>

app/views/admin/products/_shots_form.html.erb
<div class="well" id="attachments">
	<%= f.label "Product Shots" %>
	<br>
	<%= f.fields_for :product_shots do |pshot| %>

	<% if pshot.object.new_record? %>
	<%= pshot.file_field :shot %>
	<%end%>

	<% unless pshot.object.new_record? %>
	<%= link_to image_tag(pshot.object.shot.url(:thumb)), pshot.object.shot.url(:medium)%>
	<br>
	<%= pshot.object.shot.url(:medium)%>
	<br>
	<%= link_to_function "Insert image into description", "insertMarkup(this,'image')", :class=> "btn btn-mini"%>
	<%end%>

	<%= pshot.link_to_remove "Remove this image", {:id=> @product.id, :class=> "btn btn-mini btn-danger"} %>
	<br>
	<br>
	<%end %>

	<%= f.link_to_add "Add another image", :product_shots, :class=> "btn btn-mini" %>
</div>

app/views/admin/products/edit.html.erb
<div class="btn-group">
<%= link_to 'Show', admin_product_path(@product), :class=>"btn btn-mini" %> 
<%= link_to 'Back', admin_products_path, :class=>"btn btn-mini" %>
</div>
<br>


<%= render 'form' %>

app/views/admin/products/index.html.erb
<%= title "Manage Catalog"%>
<legend>Manage Catalog</legend>
<div class="row">
<span class="span6">
		<%= link_to 'New Product', new_admin_product_path, :class=>"btn"%>
</span>	
</div>
<br>
<div class="row">
	
	<% @products.each do |product| %> 
	<span class="span5"> 
		
		<h3><%= product.name %></h3> 
		<%= product.description %>
		<br>
		<% product.product_categories.each do |cat|%> <h5><%= cat.title%></h5> <%end%>
		<hr>
		
		<!-- product shots --> 
		<% product.product_shots.each do |pshot| %>
		<%= image_tag pshot.shot.url(:thumb) %>
		<%end%>
		<br>
		<br>
		
		<!-- variants -->
		<div class="submodule">
			Variants:
			<table class="table table-striped">
				<% product.variants.each do |variant| %>
				<tr>
					<td><h4><%= variant.name %></h4></td>
					<td> 
					<% variant.attributions.each do |attr|%> 
					
					<h6>
					<%= attr.trait.name%>:
					<%= attr.value%><br>
					<% variant.digitalfiles.each do |df|%>
					<%= link_to "S3 Link", df.authenticated_url(10), :class=>"label label-info"%>
					<%end %>
					</h6> 
					
					<%end %> 
					</td>
					
					<td>
					<div class="btn-group">
						<%= link_to 'Edit', edit_admin_product_path(product) , :class=>"btn btn-mini"%>
						<%= link_to 'Destroy', admin_variant_path(variant), :confirm => 'Are you sure?', :method => :delete, :class=>"btn btn-mini btn-danger" %>
					</div>
					</td>
					<%end%>
				</tr>
			</table>
		</div>
		
		
		
		<div class="btn-group">
			<%= link_to 'Add a variant', new_admin_product_variant_path(product), :class=>"btn btn-small"%>

			<%= link_to 'Show', admin_product_path(product), :class=>"btn btn-small" %>
			<%= link_to 'Edit', edit_admin_product_path(product) , :class=>"btn btn-small"%>
			<%= link_to 'Destroy', admin_product_path(product), :confirm => 'Are you sure?', :method => :delete, :class=>"btn btn-small btn-danger" %>
		</div> 
	</span>
	<% end %>
</div>
<br />

app/views/admin/products/new.html.erb
<%= render 'form'%>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<% @product.productShots.each do |pshot|%>
<%= image_tag pshot.shot.url(:thumb) %>
<%end%>

<br><br>






<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>